version: "3.8"

services:

  influxdb2:
    image: influxdb:2
    container_name: influxdb2
    restart: unless-stopped
    ports:
      - 8086:8086

    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: docs
      DOCKER_INFLUXDB_INIT_BUCKET: home

    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token

    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2

    networks:
      - historian-net

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: unless-stopped
    ports:
      - "1880:1880"

    environment:
      - TZ=America/Mexico_City

    volumes:
      - type: volume
        source: node-red-data
        target: /data

    networks:
      - historian-net

  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: timescaledb
    restart: unless-stopped
    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: password

    secrets:
      - timescaledb-password

    volumes:
      - type: volume
        source: timescaledb-data
        target: /home/postgres/pgdata/data

    networks:
      - historian-net

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"

    volumes:
      - type: volume
        source: grafana-data
        target: /var/lib/grafana

    networks:
      - historian-net

  metabase:
    image: metabase/metabase
    container_name: metabase
    restart: unless-stopped
    ports:
      - "12345:3000"

    volumes:
      - type: volume
        source: metabase-data
        target: /var/lib/metabase

    environment:
      - MB_DB_FILE=/var/lib/metabase/metabase.db

    networks:
      - historian-net

volumes:
  grafana-data:
  timescaledb-data:
  metabase-data:
  node-red-data:
  influxdb2-config:
  influxdb2-data:

secrets:
  influxdb2-admin-username:
    file: ./influxdb_setup/.env.influxdb2-admin-username
  influxdb2-admin-password:
    file: ./influxdb_setup/.env.influxdb2-admin-password
  influxdb2-admin-token:
    file: ./influxdb_setup/.env.influxdb2-admin-token
  timescaledb-password:
    file: ./timescaledb_setup/.env.timescaledb-password

networks:
  historian-net: