services:

  influxdb2:
    image: influxdb:2
    container_name: influxdb2
    restart: unless-stopped
    ports:
      - 8086:8086

    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2

    networks:
      - historian-net

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000

    volumes:
      - grafana-storage:/var/lib/grafana

    networks:
      - historian-net

  data-generator:
    build: 
      context: ./data_generator
      dockerfile: Dockerfile
    container_name: data-generator
    restart: unless-stopped
    depends_on:
      - influxdb2
    networks:
      - historian-net

  questdb:
    image: questdb/questdb:8.2.3
    container_name: questdb
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9009:9009
      - 8812:8812
      - 9003:9003
    volumes:
      - questdb-data:/var/lib/questdb
    networks:
      - historian-net

volumes:
  influxdb2-config:
  influxdb2-data:
  grafana-storage:
  questdb-data:

networks:
  historian-net: