num_registros: -1  # -1 means run indefinitely
intervalo_segundos: 5

mediciones:
  - measurement: FT010205
    unidad: filtro_2
    maquina: filtro
    subarea: filtracion
    pv:
      min: 0.0
      max: 100.0
    sp:
      min: 0.0
      max: 100.0
    cv:
      min: 0
      max: 3
